### ISSUE TITLE
Upgrade symfony components to version 4

### ISSUE THREAD

**Issue by Gemorroj** [staempfli/universal-code-generator#1]

**Comment by jalogut** [comment]
Hello @Gemorroj 

Could you provide a description or be a bit more specific about why this is an issue? Thanks

**Comment by Gemorroj** [comment]
https://github.com/magento/magento2/blob/2.3-develop/composer.json#L50
magento2.3 will only support symfony4.1+
in any case, support for symfony 4 will need to be done.

**Comment by jalogut** [comment]
PR from @piotrkwiecinski has been merged in version `1.2.3`. Tool is now compatible with symfony 4
